# Dependencies
markdown:         kramdown
# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "ember Etches*"
tagline:          "tor information & updates!"
description:      "Built by the Tor Project"
url:              "https://writerthethinker1.github.io/"
baseurl:          "/emberEtches/"
images: "ember-storage/ember_pics"
date_format: "%B %-e, %Y"

paginate:         4


# git_url: "https://github.com/writerthethinker1/emberEtches/"

# generate social links in about page.
social_links:
  twitter: torproject
  # github:
  rss: RSS
  # dribbble:
 #facebook:
  # flickr:
  # instagram:
  linkedin: company/tor-project
  # pinterest:
  # youtube:
  # youtube_channel:
  # youtube_channel_name:
  # telegram:
  # googleplus:
  # microdotblog:
  #reddit:
  # tumblr:


# Custom vars
version:          2.1.1

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
#- jekyll-seo-tag
