# Dependencies
markdown:         kramdown
# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Silver Press *"
tagline:          "question freely"
description:      "It's time for the truth! We explore heated topics rationally."
url:              "https://writerthethinker1.github.io/"
baseurl:          "/silver_press/"
images: "silver-storage/silver_pics"
date_format: "%B %-e, %Y"

paginate:         4


git_url: "https://github.com/writerthethinker1/silver_press/"

# generate social links in about page.
social_links:
  #twitter:
  # github:
  rss: RSS
  # dribbble:
 #facebook: Ramneek Narayan
  # flickr:
  # instagram:
  # linkedin:
  # pinterest:
  # youtube:
  # youtube_channel:
  # youtube_channel_name:
  # telegram:
  # googleplus:
  # microdotblog:
  #reddit:
  # tumblr:


# Custom vars
version:          2.1.1

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
#- jekyll-seo-tag
