# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://github.com/writerthethinker1/silver_press/
baseurl:          /silver_press/

author:
  name:           'free thinker'
  url:            https://github.com/writerthethinker1/silver_press/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/writerthethinker1/silver_press/
