# Dependencies
markdown:         kramdown
# Permalinks
permalink:        pretty
relative_permalinks: false

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title:            'Silver Press *'
tagline:          'question freely'
description:      'A press dedicated to original thought. We explore controversial topics academically, with reason.'
url:              https://github.com/writerthethinker1/
baseurl:          /silver_press/

author:
  name:           'free+thinker'
  url:            https://github.com/writerthethinker1/silver_press/

paginate:         4

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/writerthethinker1/silver_press/
